# Generated by Django 4.1.9 on 2023-07-20 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("meet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagencollection",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="imagencollection",
            name="imagen",
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name="imagencollection",
            name="nombre",
            field=models.CharField(max_length=255),
        ),
    ]
