import "../style/globals.css";
import { Inter } from "next/font/google";
import NavBar from "@/components/navigation/navBar";
import Footer from "@/components/navigation/footer";
import Alert from "@/components/alert/alert";
import { Providers } from "@/redux/provider";
import Script from "next/script";
import { GoogleAnalytics, GoogleTagManager } from "@/components/google/scripts";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GoogleAnalytics/>
      <GoogleTagManager/>
      
      <body className={`${inter.className} bg-gray-950`}>
        <Providers>
          <NavBar />
          <Alert />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
