import "../style/globals.css";
import { Inter } from "next/font/google";
import NavBar from "@/components/navigation/navBar";
import Footer from "@/components/navigation/footer";
import Alert from "@/components/alert/alert";
import { Providers } from "@/redux/provider";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Script
        strategy="afterInteractive"
        src="https://www.googletagmanager.com/gtag/js?id=G-8NJ5Z0LCJV"
      />
      <Script
        id="google-analytics"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
          window.dataLayer = window.dataLayer || []; function gtag()
          {dataLayer.push(arguments)}
          gtag('js', new Date()); gtag('config', 'G-8NJ5Z0LCJV');
                `,
        }}
      />

      <body className={`${inter.className} bg-gray-950`}>
        <Providers>
          <NavBar />
          <Alert />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
